### ISSUE TITLE
Can't place or receive calls

### ISSUE THREAD

**Issue by Thetechguru-net** [Jerrkawz/google-voice-desktop-app#1]
Get an error that the browser does not support internet calling.  Works from the web page on Chrome on same Windows 10 machine.

Google Voice Help indicates that calling is only supported on Chrome and Firefox, but I believe that is out of date sine it also works on M$ Edge since it updated to Chromium based.

**Comment by Jerrkawz** [comment]
Fixed with commit 6dddb40 and release 1.0.1
