### ISSUE TITLE
Clicking voice icon does not open voice.

### ISSUE THREAD

**Issue by brmonaghan** [Jerrkawz/google-voice-desktop-app#10]
Sorry for being a problem @Jerrkawz and @joshnovak ! I have one more thing that does NOT work, the voice icon in the taskbar.
It does not open upon clicking it. I want this to open voice when clicking this.
@joshnovak can you attempt to fix this and PR this to the main form?
or can this be fixed by you, @Jerrkawz ?
Thanks

**Comment by Jerrkawz** [comment]
He coded it up as double clicking will open, so technically its working as designed but i think I agree, id like it to open on a single click. Also double clicking doesn't work on mac osx either. Whoever has time can fix this, it should be as simple as changing line 147 from 'double-click' to click, but needs to be tested on mac and windows.

**Comment by brmonaghan** [comment]
Ok, thank you!

**Comment by brmonaghan** [comment]
@Jerrkawz I will write the single line on my fork of the project, and then make a PR to your project. You can tag along @joshnovak

**Comment by brmonaghan** [comment]
build done. now testing

**Comment by brmonaghan** [comment]
Works. Also changed refresh rate for new messages to 1 sec instead of 5

**Comment by brmonaghan** [comment]
sending pr right now for you to review.

**Comment by brmonaghan** [comment]
#12 now available for you to review @Jerrkawz

**Comment by brmonaghan** [comment]
If this is okay, We can close it.

**Comment by brmonaghan** [comment]
Closing as this is fixed in my build of gv desktop. More info on my fork of gv desktop [](https://github.com/brmonaghan/google-voice-desktop-app)
