### ISSUE TITLE
Add close button for text messages, and add answer and decline options for calls

### ISSUE THREAD

**Issue by brmonaghan** [Jerrkawz/google-voice-desktop-app#11]
Just like the old hangouts experience, i would like this to happen
Add close button for new messages and set notification timeout to 5 minutes (priority)
and also, add Answer and decline options to notifications when a call is received (priority too)
This may be impossible because of Voice's notifications being shown.

**Comment by Jerrkawz** [comment]
Yeah this is pretty much next to impossible because im just wrapping the voice app, its not some experience thats integrated with their APIs at all, its very much just hacked on top

**Comment by brmonaghan** [comment]
Ok, closing as this is impossible.
