### ISSUE TITLE
Voice opens new instance when closed to taskbar.

### ISSUE THREAD

**Issue by brmonaghan** [Jerrkawz/google-voice-desktop-app#17]
Google Voice is got a problem
It opens a new instance when closed to the taskbar.
It makes a double execution with two voice icons on sidebar.

**Comment by Jerrkawz** [comment]
I dont see this behavior. Try 1.1.4, if its still happening then you may reopen but please include repro steps along with system information.

**Comment by brmonaghan** [comment]
@Jerrkawz i have made new thread since you closed this and I cannot reopen. See #23 for details
