### ISSUE TITLE
Error after installing 1.1.13

### ISSUE THREAD

**Issue by Bwangster12** [Jerrkawz/google-voice-desktop-app#19]
I get a Javascript error occured in the main process error after installing and then launching the app.

![image](https://user-images.githubusercontent.com/26938129/100768788-47254500-33c9-11eb-9ecb-6e4682d16cb3.png)

**Comment by Seedless** [comment]
I received the same error message.  If I replace the app.asar from version 1.0.4 it will open without the error, but if I put the app.asar from 1.1.3 back in place I get the error.  

1.0.4 section:
![Windows](/images/windows.png?raw=true")
{
  "name": "voice-desktop-app",
  "version": "1.0.4",
  "description": "An electron shell wrapper for the google voice app",
  "main": "src/main.js",
  "author": "jllankfo@ncsu.edu",
  "license": "ISC"
}// Copied from https://github.com/viktor-shmigol/electron-windows-badge

1.1.3
and perhaps it makes sense to pull out another component by itself.{
  "name": "voice-desktop-app",
  "version": "1.1.3",
  "description": "An electron shell wrapper for the google voice app",
  "main": "src/main.js",
  "author": "jllankfo@ncsu.edu",
  "license": "ISC"
}// Copied from https://github.com/viktor-shmigol/electron-windows-badge

**Comment by Seedless** [comment]
1.1.4 seems to have fixed my issue.

**Comment by Jerrkawz** [comment]
Yes sorry 1.1.3 shouldn't have been released, it was busted.
