### ISSUE TITLE
Check if already running

### ISSUE THREAD

**Issue by jcouch93** [Jerrkawz/google-voice-desktop-app#22]
I have a link to the exe in my Quick Launch bar, but I've noticed that if I forget and click on that the program gets launched again (even if it's already opened and in the tray).  Can it be modified to check if, when the exe is ran, it is already running and open the already running instance instead?  Thanks for this awesome program!

**Comment by brmonaghan** [comment]
See #17 and #23 for details. @Jerrkawz this person has the same problem as me.
![notworkgv](https://user-images.githubusercontent.com/71337477/100925569-284dae00-34b0-11eb-86c7-920c0762a8f9.gif)
Are you talking about the above screengrab?

**Comment by jcouch93** [comment]
> 
> 
> See #17 and #23 for details. @Jerrkawz this person has the same problem as me.
> ![notworkgv](https://user-images.githubusercontent.com/71337477/100925569-284dae00-34b0-11eb-86c7-920c0762a8f9.gif)
> Are you talking about the above screengrab?

Yes.  I apologize for opening another tkt for something already identified.  You can close this one since the others are already open.  Thank you!

**Comment by brmonaghan** [comment]
Closing will be handled via @Jerrkawz as I do not have permission to close issues.
