### ISSUE TITLE
Still not working see #17 for details

### ISSUE THREAD

**Issue by brmonaghan** [Jerrkawz/google-voice-desktop-app#23]
Google Voice is got a problem
It opens a new instance when closed to the taskbar.
It makes a double execution with two voice icons on sidebar.
In 1.1.4, this still doesnt work.
![notworkgv](https://user-images.githubusercontent.com/71337477/100925233-baa18200-34af-11eb-8992-93493de2568e.gif)
The gif above shows the problems
1. go to google voice desktop app and open up
2. Close gv with close button.
3. Open google voice again, and it makes a new instance.
NOTE: this only works when you pin GV to taskbar.

**Comment by Jerrkawz** [comment]
Fixed by 41dfc55 and release 1.1.5
