### ISSUE TITLE
Community interaction

### ISSUE THREAD

**Issue by CarsondaCoolest** [Jerrkawz/google-voice-desktop-app#3]
I would love to see a place for people to get together to discuss this incredible project. Have you considered a Discord server?

**Comment by Jerrkawz** [comment]
Sure ill set something up, in the mean time you can file issues for ideas

**Comment by brmonaghan** [comment]
Whats the status for this? I would help in by making the discord! @jerrkawz you can add me as a moderator if you wish.

**Comment by Jerrkawz** [comment]
@CarsondaCoolest @brmonaghan here you go: https://discord.gg/htpzmxz9

I wont need mods for a 4 person channel, if it starts growing rapidly for whatever reason ill let you know

**Comment by brmonaghan** [comment]
Okie doke!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
