### ISSUE TITLE
Clicking notification doesn't open app

### ISSUE THREAD

**Issue by Bwangster12** [Jerrkawz/google-voice-desktop-app#4]
Clicking on a desktop notification when a text is received doesn't open the app.  Nothing happens and you have to manually open the app.

**Comment by Jerrkawz** [comment]
Which OS? Works for me on osx

**Comment by Bwangster12** [comment]
Windows 10

**Comment by lazyb5** [comment]
I can confirm is doesn't open app for me on windows 10.

**Comment by Jerrkawz** [comment]
This should be fixed by e4a001 but i won't close it until i do a new release

**Comment by Jerrkawz** [comment]
Fixed in 1.0.3

**Comment by rpodric** [comment]
It doesn't seem to work on Win10 in 1.1.6, though, but I think it did in 1.1.5.
