### ISSUE TITLE
Windows protected your PC message

### ISSUE THREAD

**Issue by brmonaghan** [Jerrkawz/google-voice-desktop-app#46]
It appears that in the latest update, v1.1.9 (v1.1.5 in Jerrkawz) shows a protected your PC message when running.
![protected pc](https://user-images.githubusercontent.com/71337477/113488296-15adaa80-948b-11eb-81c9-e7395b8c9d9d.png)

**Comment by rpodric** [comment]
That's a pretty normal overreaction for EXEs it's never seen before. Just make an exception for it in Defender if "Run anyway" isn't permanent.

**Comment by brmonaghan** [comment]
ok.
