### ISSUE TITLE
Customization button not responsive

### ISSUE THREAD

**Issue by costacola** [Jerrkawz/google-voice-desktop-app#48]
Great app and thanks to you!
I wanted to add a theme skin to the app but the customize button does not open anything.  I'm on a windows 10 machine, opened Voice desktop as admin in case it was an issue but same behavior regardless.  Let me know when an update rolls out.  Thanks and great work!

**Comment by DarylO71** [comment]
I don't even see a customisation button.  I'm running the AppImage for Ubuntu.

**Comment by RonOnThePond** [comment]
Same for me. Just installed 1.1.6 for Windows 10. I see the customization button, but it does nothing.

**Comment by Bwangster12** [comment]
Yeah, I had the "Dracula" theme on the prior version, and still do after the update... but the customization button doesn't work to let me change it.

**Comment by jeffjensen** [comment]
I confirm the same issue.  After upgrading, the menu option was non-responsive.  After running for a bit, the menu option no longer exists.

**Comment by RonOnThePond** [comment]
> Same for me. Just installed 1.1.6 for Windows 10. I see the customization button, but it does nothing.

1.1.7 works now. That was quick! Thanks!

**Comment by costacola** [comment]
Yes the most recent update fixed the bug.  Great work.  Thanks for the quick fix!

**Comment by DarylO71** [comment]
I installed the latest update for Ubuntu, and although there's now a 'Customize' button, it doesn't do anything.
