### ISSUE TITLE
Customize Button Not Functioning in Ubuntu

### ISSUE THREAD

**Issue by DarylO71** [Jerrkawz/google-voice-desktop-app#52]
I have the latest version (Voice Desktop 1.1.7) running in Ubuntu, and although the Customize button now appears, it is non-functional.  Is this a permissions issue?  I'd rather not run this app as root.  Thank you.

**Comment by br14nw** [comment]
It's missing in the Windows install as well.

**Comment by DarylO71** [comment]
@br14nw Are you running the latest version?  I don't know why the other issue was closed if it's still a problem in Windows, too.

**Comment by br14nw** [comment]
Yep. Downloaded and installed Voice-Desktop-Setup-1.1.7-WindowsX64.exe this morning.

**Comment by br14nw** [comment]
I restarted the app and the customize option popped up for me. It appears to function. I'll keep an eye on it and report back if it drops off again.

**Comment by DarylO71** [comment]
After I rebooted, the issue resolved itself.
