### ISSUE TITLE
Received a security upon running version 1.1.7

### ISSUE THREAD

**Issue by jbweisberg** [Jerrkawz/google-voice-desktop-app#54]
Great app you created, only concern is this security alert. Here is screenshot of the alert received. Please advise. Thank you

![image](https://user-images.githubusercontent.com/14256293/113737726-4af50b00-96cc-11eb-8a5c-2fad8faea64f.png)

**Comment by rpodric** [comment]
The browser ID that the app uses is indeed Mac, so Google sees it as a new system and warns you.

**Comment by jbweisberg** [comment]
Thank you for the clarification!

I read further on the reddit where I learned of your app and another party
suggested:

Go to "More tools / Create shortcut..." and check "Open as window". This
will create a shortcut on your desktop that opens Google Voice in a
separate, non-tabbed window so it looks like an app. It also makes it
available on the Apps page. If you do it this way, you can also pin it to
Start menu or the taskbar.

Is the end result different than your app?

Thanks,
JB

--

@jbweisberg

**Comment by rpodric** [comment]
It's not my app, and I don't know the answer to that. It should be really similar though and is easy enough to test out.

**Comment by jbweisberg** [comment]
I figured you were the developer. That's very kind of you to get back to
me. Yes, it seems similar enough.



--
www.fluidverified.com
<http://s.bl-1.com/h/cPJYcFBw?url=http://www.f8020.net>
Better Marketing. Verified.™

@jbweisberg

**Comment by rpodric** [comment]
One difference is the ability of this app to use the tray, where that other way would be relegated to the taskbar.

Also, you'd have to test notifications, including ringing if you get calls. One reason I started using this app is that voice.google.com in my browser doesn't do well for those things at all when I'm not on that tab.

**Comment by jbweisberg** [comment]
good points will see what the differences are and let you know too

--
www.fluidverified.com
<http://s.bl-1.com/h/cPJYcFBw?url=http://www.f8020.net>
Better Marketing. Verified.™

@jbweisberg

**Comment by brmonaghan** [comment]
@jerrkawz is the developer @jbweisberg and may be able to help you.

**Comment by Jerrkawz** [comment]
System tray and the customization (themes, zoom, potentially others in the future) are the only real differences
