### ISSUE TITLE
32-bit Windows Version for ARM based 2-in-1's/Laptops

### ISSUE THREAD

**Issue by azeame** [Jerrkawz/google-voice-desktop-app#55]
Is there a way to provide a 32-bit Windows build? I have a Galaxy Book 2 which uses a Snapdragon 8xx arm processor. which does not have the ability to run most 64-bit apps.

**Comment by brmonaghan** [comment]
@azeame try using [this](https://github.com/brmonaghan/google-voice-desktop-app/releases/tag/v1.2.1) build that is universal with 64 and 32bit computers. I will try to incorporate that into my release in the coming days.

**Comment by azeame** [comment]
@brmonaghanThanks for the reply, I just tried it and received a message after the installer appearing to finish which says "This file does not have an app associated with it for performing this action. Please install an app or, if one already installed, create an association in the Default Apps Settings page."

The notification comes from "C:\Users\<USER>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Voice Desktop..." I can't see the full path.

When I try to run it anyway, it tells me "This App Can't Run on Your PC. Find a version for your PC, check with the software publisher."

I've tried quite a few compatibility options, but I get no where with it. The option to change the compatibility mode for Windows on Arm is not available to change although I'm an admin.

I hope this helps, thanks.

**Comment by brmonaghan** [comment]
Ok, I have released 1.2.2 and will be linking it soon.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by brmonaghan** [comment]
Done. now available in @brmonaghan/google-voice-desktop-app
see [here](https://github.com/brmonaghan/google-voice-desktop-app/releases/tag/v1.2.2) for updated info. also uses web to save time.

**Comment by brmonaghan** [comment]
if it works okay, you can close the issue.

**Comment by azeame** [comment]
Unfortunately, that didn't work either, but I'm coming into this knowing that the Qualcomm Snapdragon 850 is a notoriously difficult processor compatibility wise, so while it would be nice, please don't feel any pressure to get it working on this specific processor, I know they didn't sell that well and it's par for the course for those of us that have them.

I appreciate the attempt I'm going to close this issue, no hard feelings. Unfortunately, after a number of years with this device I have an expectation that programs outside the MS Store are going to be very hit and miss.

I'll let you or someone else revive this if it seems warranted.

**Comment by brmonaghan** [comment]
Sorry I cant help you with ARM processors because they are not compatible with GVoice.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by azeame** [comment]
No worries my experience with this thing is to expect that nothing will work for it, and then be pleasantly surprised when something works without issues. Over the years I have come to find that this processor probably should have never left beta as the problem and has nothing to do with the work that you are doing. I will continue to use your desktop version on my main PC until I find a suitable LTE replacement.
