### ISSUE TITLE
Put voice in background without closing entire app

### ISSUE THREAD

**Issue by brmonaghan** [Jerrkawz/google-voice-desktop-app#6]
Please add option to place voice in background without having to close the entire application. That way you will not miss calls.

**Comment by Jerrkawz** [comment]
Whats wrong with keeping it minimized? The problem with running it in the background is that I need the window open because the way the notifications work is that Im scraping the actual page for the notification bubbles and updating the dock / taskbar icon. So without an actual running page its not going to function properly

**Comment by brmonaghan** [comment]
When I close it it does not minimize, it closes. Missed out on a important phone call.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by joshnovak** [comment]
I tried to address this by minimizing to the systray - submitted a pull request.  
I'd like to know if this addresses this issue.  Thanks!

**Comment by brmonaghan** [comment]
Still does not work properly no systray at all. I do not approve this yet till this is fixed.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by joshnovak** [comment]
Works good for me - but maybe it's your environment.  Can you provide any details for what is happening??

**Comment by brmonaghan** [comment]
Tried to send via email but failed.
I launch voice with npm in git, it launches and when I close it, it closes with no notification.

**Comment by brmonaghan** [comment]
![image](https://user-images.githubusercontent.com/71337477/99844309-e5e7b100-2b40-11eb-9ee4-821671f1e8ce.png)

**Comment by brmonaghan** [comment]
BUT! When it minimizes, it seems to work. Please fix the close button so it MINIMIZES TO SYSTRAY! then I can approve.

**Comment by brmonaghan** [comment]
![image](https://user-images.githubusercontent.com/71337477/99844410-06b00680-2b41-11eb-84ef-e2d81e100520.png)

**Comment by joshnovak** [comment]
Ahhh... that was by design... you need to be able to close the app.

The change was to MINIMIZE to the systray, otherwise you cannot close/exit the app.

**Comment by brmonaghan** [comment]
Yeah but you can close it via the systray.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Jerrkawz** [comment]
Yeah I think i agree, it should be on close and you can still close via system tray.

**Comment by brmonaghan** [comment]
THANK YOU SO MUCH @joshnovak ! It worked!

**Comment by brmonaghan** [comment]
CLOSING as this works!

**Comment by brmonaghan** [comment]
for anyone who is stumbled with this, just download @joshnovak 's variant of GV desktop. I WANT TO GIVE @joshnovak A BIG KUDOS TO HELPING OUT THE HANGOUTS COMMUNITY!

**Comment by brmonaghan** [comment]
now @joshnovak needs to make a release for the commit. how do you convert a electron app to an exe?

**Comment by joshnovak** [comment]
I'm going to let @Jerrkawz hopefully pull in the change and create a release.

To make an EXE, I used electron-packager.
Basically, these commands,

  npm install -g electron-packager --save-dev
  electron-packager .

That's it.

**Comment by brmonaghan** [comment]
HOLY SHIITAKE YOU ARE THE BEST. THANK YOU @joshnovak FOR GIVING ME THIS!

**Comment by rpodric** [comment]
That's an important feature, thanks.

Related to that though is the ability to start the app minimized (to the tray, or course) in the first place (i.e. automatically), such as when starting the PC or logging in. Perhaps with a switch to the command line? Just a thought.
