### ISSUE TITLE
Any plan to support hangouts integration as well?

### ISSUE THREAD

**Issue by robertleeplummerjr** [Jerrkawz/google-voice-desktop-app#7]
Just curios.

**Comment by lazyb5** [comment]
why? Hangouts is gone soon. That's the whole reason for this being made.

**Comment by Jerrkawz** [comment]
^ This

**Comment by Jerrkawz** [comment]
Although you could add a tab inside the window to easily switch back and forth between google chat, maybe thats what you meant. Its crossed my mind to do that, personally i dont use chat anymore so its not a priority

**Comment by robertleeplummerjr** [comment]
ok, fair enough.
